import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { CarFront, CircleUserRound, Gauge, LogOut, Plus, Search, ShieldCheck, SlidersHorizontal, X } from 'lucide-react'
import './styles.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const demoVehicles = [
  { id: 1, make: 'Porsche', model: '911 Carrera', category: 'Sports', price: 126000, quantity: 2 },
  { id: 2, make: 'Range Rover', model: 'Velar Dynamic', category: 'SUV', price: 68900, quantity: 4 },
  { id: 3, make: 'Mercedes-Benz', model: 'S 580 4MATIC', category: 'Luxury', price: 128400, quantity: 1 },
  { id: 4, make: 'Tesla', model: 'Model S Plaid', category: 'Electric', price: 89990, quantity: 0 },
]
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })

function api(path, method = 'GET', body, token) {
  return fetch(`${API}${path}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }).then(async r => {
    const data = r.status === 204 ? null : await r.json()
    if (!r.ok) throw new Error(data?.detail || 'Something went wrong')
    return data
  })
}

function AuthPanel({ onSuccess }) {
  const [mode, setMode] = useState('login'), [form, setForm] = useState({ name: '', email: '', password: '' }), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  const submit = async e => { e.preventDefault(); setLoading(true); setError(''); try { const path = mode === 'login' ? '/api/auth/login' : '/api/auth/register'; const payload = mode === 'login' ? { email: form.email, password: form.password } : form; const result = await api(path, 'POST', payload); if (mode === 'login') onSuccess(result); else { setMode('login'); setError('Account created. Please sign in.'); } } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <main className="auth-shell"><section className="auth-story"><div className="brand"><CarFront size={27} /><span>APEX<span className="text-gold">MOTORS</span></span></div><p className="eyebrow">EXCEPTIONAL, BY DESIGN</p><h1>Inventory,<br /><em>elevated.</em></h1><p className="story-copy">A considered workspace for the modern dealership—where every detail moves with intent.</p><div className="story-stat"><b>240+</b><span>vehicles curated<br />across four collections</span></div></section><section className="auth-card"><div><p className="eyebrow text-gold">WELCOME TO APEX</p><h2>{mode === 'login' ? 'Sign in to your account' : 'Create your account'}</h2><p className="muted">{mode === 'login' ? 'Access the showroom inventory.' : 'Start exploring the collection.'}</p></div><form onSubmit={submit}>{mode === 'register' && <label>Full name<input required minLength="2" placeholder="Your name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label>}<label>Email address<input required type="email" placeholder="name@example.com" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required minLength="8" type="password" placeholder="••••••••" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="form-message">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'} <span>→</span></button></form><p className="switcher">{mode === 'login' ? 'New to Apex?' : 'Already registered?'} <button onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></section></main>
}

export function VehicleCard({ vehicle, onPurchase, admin, onEdit }) { const out = vehicle.quantity === 0; return <article className="vehicle-card"><div className={`car-art art-${vehicle.id % 4}`}><CarFront strokeWidth={1.1} size={88} /><span>{vehicle.category}</span></div><div className="vehicle-info"><div><p className="vehicle-make">{vehicle.make}</p><h3>{vehicle.model}</h3></div><p className="price">{money.format(vehicle.price)}</p></div><div className="vehicle-footer"><span className={out ? 'stock out' : 'stock'}>{out ? 'Out of stock' : `${vehicle.quantity} in stock`}</span>{admin ? <button className="secondary" onClick={() => onEdit(vehicle)}>Manage</button> : <button disabled={out} className="secondary" onClick={() => onPurchase(vehicle)}>{out ? 'Unavailable' : 'Purchase'}</button>}</div></article> }

function VehicleForm({ vehicle, onClose, onSave, onDelete, onRestock }) { const [form, setForm] = useState(vehicle || { make: '', model: '', category: 'SUV', price: '', quantity: 1 }); const [restockQty, setRestockQty] = useState(1); const submit = e => { e.preventDefault(); onSave({ ...form, price: Number(form.price), quantity: Number(form.quantity) }) }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={onClose}><X /></button><p className="eyebrow text-gold">ADMIN INVENTORY</p><h2>{vehicle ? 'Update vehicle' : 'Add a vehicle'}</h2><div className="grid-fields"><label>Make<input required value={form.make} onChange={e => setForm({ ...form, make: e.target.value })} /></label><label>Model<input required value={form.model} onChange={e => setForm({ ...form, model: e.target.value })} /></label><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{['SUV', 'Sports', 'Luxury', 'Electric', 'Sedan'].map(x => <option key={x}>{x}</option>)}</select></label><label>Price<input required min="1" type="number" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} /></label><label>Stock quantity<input required min="0" type="number" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></label></div>{vehicle && <div className="restock-row"><label>Quick restock<input min="1" type="number" value={restockQty} onChange={e => setRestockQty(e.target.value)} /></label><button type="button" className="secondary" onClick={() => onRestock(vehicle, Number(restockQty))}>Add stock</button></div>}<div className="modal-actions"><button className="primary">Save vehicle <span>→</span></button>{vehicle && <button type="button" className="danger" onClick={() => onDelete(vehicle)}>Delete</button>}</div></form></div> }

function Dashboard({ session, onLogout }) {
  const [vehicles, setVehicles] = useState([]), [search, setSearch] = useState(''), [category, setCategory] = useState('All'), [notice, setNotice] = useState(''), [modal, setModal] = useState(null)
  const admin = session.user.role === 'admin'
  useEffect(() => { api('/api/vehicles', 'GET', null, session.access_token).then(r => setVehicles(r.items)).catch(() => setVehicles(demoVehicles)) }, [])
  const filtered = useMemo(() => vehicles.filter(v => `${v.make} ${v.model}`.toLowerCase().includes(search.toLowerCase()) && (category === 'All' || v.category === category)), [vehicles, search, category])
  const purchase = async v => { try { const updated = await api(`/api/vehicles/${v.id}/purchase`, 'POST', null, session.access_token); setVehicles(xs => xs.map(x => x.id === v.id ? updated : x)); setNotice(`${v.make} ${v.model} reserved successfully.`) } catch (e) { setNotice(e.message) } }
  const restock = async (vehicle, quantity) => { try { const updated = await api(`/api/vehicles/${vehicle.id}/restock`, 'POST', { quantity }, session.access_token); setVehicles(xs => xs.map(x => x.id === updated.id ? updated : x)); setModal(updated); setNotice(`${quantity} units added to inventory.`) } catch (e) { setNotice(e.message) } }
  const remove = async vehicle => { if (!window.confirm(`Delete ${vehicle.make} ${vehicle.model}? This cannot be undone.`)) return; try { await api(`/api/vehicles/${vehicle.id}`, 'DELETE', null, session.access_token); setVehicles(xs => xs.filter(x => x.id !== vehicle.id)); setModal(null); setNotice('Vehicle removed from inventory.') } catch (e) { setNotice(e.message) } }
  const save = async data => { try { const updated = await api(modal?.id ? `/api/vehicles/${modal.id}` : '/api/vehicles', modal?.id ? 'PUT' : 'POST', data, session.access_token); setVehicles(xs => modal?.id ? xs.map(x => x.id === updated.id ? updated : x) : [updated, ...xs]); setModal(null); setNotice('Inventory updated.') } catch (e) { setNotice(e.message) } }
  return <div className="app-shell"><header><div className="brand"><CarFront size={24} /><span>APEX<span className="text-gold">MOTORS</span></span></div><nav><a className="active">Inventory</a><a>Insights</a><a>Orders</a></nav><div className="profile"><span className="role"><ShieldCheck size={15} /> {admin ? 'Administrator' : 'Client access'}</span><CircleUserRound size={23} /><button aria-label="Sign out" onClick={onLogout}><LogOut size={18} /></button></div></header><main className="dashboard"><section className="hero"><div><p className="eyebrow text-gold">THE COLLECTION</p><h1>Find your next<br /><em>exceptional</em> drive.</h1><p>Explore our precisely curated inventory of performance, luxury, and electric vehicles.</p></div><div className="hero-metric"><Gauge size={22} /><b>{vehicles.length || '—'}</b><span>vehicles<br />in inventory</span></div></section><section className="toolbar"><div className="search"><Search size={19} /><input placeholder="Search make or model" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="filters"><SlidersHorizontal size={18} />{['All', 'SUV', 'Sports', 'Luxury', 'Electric'].map(x => <button className={category === x ? 'selected' : ''} key={x} onClick={() => setCategory(x)}>{x}</button>)}</div>{admin && <button className="add-button" onClick={() => setModal({})}><Plus size={18} /> Add vehicle</button>}</section>{notice && <div className="notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}<div className="results"><p><b>{filtered.length}</b> vehicles available</p><span>Showing curated inventory</span></div><section className="inventory-grid">{filtered.map(v => <VehicleCard key={v.id} vehicle={v} onPurchase={purchase} admin={admin} onEdit={setModal} />)}</section></main>{modal && <VehicleForm vehicle={modal.id ? modal : null} onClose={() => setModal(null)} onSave={save} onDelete={remove} onRestock={restock} />}</div>
}

export function App() { const [session, setSession] = useState(() => { try { return JSON.parse(localStorage.getItem('apex-session')) } catch { return null } }); const enter = data => { localStorage.setItem('apex-session', JSON.stringify(data)); setSession(data) }; const leave = () => { localStorage.removeItem('apex-session'); setSession(null) }; return session ? <Dashboard session={session} onLogout={leave} /> : <AuthPanel onSuccess={enter} /> }
const root = document.getElementById('root')
if (root) createRoot(root).render(<App />)
